### ISSUE TITLE
Extend parsers to include Fitbit Intraday

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/quantified-flu#5]
Last week I made a notebook that uses both the Fitbit intraday as well as the regular Fitbit data sources to merge them into one nightly HR distribution for more granular data, see https://exploratory.openhumans.org/notebook/85/ 

The notebook is not practical right now as it runs forever, as I couldn't figure out a smart way to match different date keys and arrays in a clever way. But it would be possible to convert the same approach into a celery task and generate graphs from this. 

It should be rather straight forward to adapt the code cells from the notebook to run as an additional parser.

**Comment by rtf-const** [comment]
Attempt to open the notebook currently returns 500 error
![image](https://user-images.githubusercontent.com/1955908/78278458-8300c580-752f-11ea-8feb-ab935b7295cf.png)

**Comment by rtf-const** [comment]
Is is there a some way to get the OH_ACCESS_TOKEN for work on this? Or can you share some anonymised pickled version of `user_details` and `fitbit_data`

**Comment by gedankenstuecke** [comment]
Hey @rtf-const, sharing the `OH_ACCESS_TOKEN` isn't possible as they give unlimited access to my own data and also expire after 24 hours. But I've attached files culled down to the data ranges of interest to this comment. The format etc is the same, so hope that helps!

[fitbit-demo-data.zip](https://github.com/OpenHumans/quantified-flu/files/4422617/fitbit-demo-data.zip)

**Comment by rtf-const** [comment]
I created modified version of your notebook https://exploratory.openhumans.org/notebook/88/

I rewrote heart rate processing method as follows:

`# Convert hr_data to pandas dataframe
rows = []
for hr_point in hr_data:
    hr_date = hr_point['date']
    for hr_datapoint in hr_point['dataset']:
        rows.append((hr_date + ' ' + hr_datapoint['time'], hr_datapoint['value']))
hr_dataframe = pd.DataFrame(rows, columns=['timestamp', 'heart_rate'])
hr_dataframe['timestamp'] = pd.to_datetime(hr_dataframe['timestamp'], utc=True)

# combine with sick days data
dataframes = []
for p in sd_dict.keys():
    for entry_date,entry in sd_dict[p]['entries'].items():
        #
        start = entry['start'].datetime
        end = entry['end'].datetime
        filtered = hr_dataframe[(hr_dataframe['timestamp'] >= start) & (hr_dataframe['timestamp'] <= end)].copy()
        filtered['period'] = p
        dataframes.append(filtered)

dataframe_new = pd.concat(dataframes).reset_index(drop=True)`

Main changes:
- instead of using nested loops for data filtering I build the pandas dataframe with raw heart rate data and than use it to get filterd data
- I replaced arrow object with native datetime, pandas doesn't work great with arrow, it treat it like an object and it makes filtering very slow

New version works in few seconds while providing the identical dataframe

**Comment by gedankenstuecke** [comment]
Thanks so much @rtf-const! I've made PR #29 based on your notebook and added you as a co-author to the commits!
